import { ContextProvider } from "@/components/client/Client";
import Header from "./Header";

export const metadata = {
  title: "Todo Application",
  description: "Generated by RRK",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ContextProvider>
          <>
            <Header />
            {children}
          </>
        </ContextProvider>
      </body>
    </html>
  );
}
